name: linkChecker

on: [push]

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Link Checker
      id: lc
      uses: peter-evans/link-checker@v1
      with:
        args: -v -r docs
        
    - name: Archive linkchecker results
      uses: actions/upload-artifact@v2
      with:
        name: link-checker-results
        path: link-checker/out.md

  publish:
    if: ${{ github.ref == 'master' }}
    needs: linkChecker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: cd docs && yarn install && yarn run deploy